yarnPath: .yarn/releases/yarn-3.3.0.cjs

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com/
    npmAuthToken: '${FONT_AWESOME_NPM_TOKEN}'
  gsap:
    npmRegistryServer: https://npm.greensock.com/
    npmAuthToken: '${GSAP_NPM_TOKEN}'
